services:
  - type: web
    name: Mo.Sajid-Portfolio-Copy
    env: python
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker app.main:app"
